import RPi.GPIO as  GPIO
import time

servoPin = 17
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(servoPin, GPIO.OUT)
p = GPIO.PWM(servoPin, 50)
p.start(6)

try:
  while True:
    # print("On")
    # p.ChangeDutyCycle(5)
    # print("changing")
    # time.sleep(5)
    # p.ChangeDutyCycle(7.5)
    # print("changing")
    # time.sleep(5)
    # p.ChangeDutyCycle(10)
    # print("changing")
    # time.sleep(5)
    # p.ChangeDutyCycle(12.5)
    # time.sleep(5)
    # p.ChangeDutyCycle(10)
    # time.sleep(5)
    # p.ChangeDutyCycle(7.5)
    # time.sleep(5)
    # p.ChangeDutyCycle(5)
    # time.sleep(5)
    # p.ChangeDutyCycle(2.5)
    # time.sleep(5)
    # p.ChangeDutyCycle(3)
    # print("3")
    # time.sleep(2)
    # p.ChangeDutyCycle(3.5)
    # print("3.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(4)
    # print("4")
    # time.sleep(2)
    # p.ChangeDutyCycle(4.5)
    # print("4.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(5)
    # print("5")
    # time.sleep(2)
    # p.ChangeDutyCycle(5.5)
    # print("5.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(6)
    # print("6")
    # time.sleep(2)
    # p.ChangeDutyCycle(6.5)
    # print("6.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(7)
    # print("7")
    # time.sleep(0.1)
    # p.ChangeDutyCycle(0)
    # time.sleep(2)
    # p.ChangeDutyCycle(7.5)
    # print("7.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(8)
    # print("8")
    # time.sleep(2)
    # p.ChangeDutyCycle(8.5)
    # print("8.5")
    # time.sleep(2)
    p.ChangeDutyCycle(9)
    print("9")
    time.sleep(0.1)
    p.ChangeDutyCycle(0)
    time.sleep(2)
    # p.ChangeDutyCycle(9.5)
    # print("9.5")
    # time.sleep(2)
    # p.ChangeDutyCycle(10)
    # print("10")
    # time.sleep(2)
    # p.ChangeDutyCycle(10.5)
    # print("10.5")
    # time.sleep(2)
    p.ChangeDutyCycle(11)
    print("11")
    time.sleep(0.1)
    p.ChangeDutyCycle(0)
    time.sleep(2)

except KeyboardInterrupt:
  p.stop()
  GPIO.cleanup()
